//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class KabinetPredmet
    {
        public int ID_KabinetPredmet { get; set; }
        public int ID_Kabinet { get; set; }
        public int ID_Predmet { get; set; }
    
        public virtual Kabinet Kabinet { get; set; }
        public virtual Predmet Predmet { get; set; }
    }
}
