//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class UchitelKlassPredmet
    {
        public int ID_UchitelKlassPredmet { get; set; }
        public int ID_Uchitel { get; set; }
        public int ID_KlassPredmet { get; set; }
    
        public virtual KlassPredmet KlassPredmet { get; set; }
        public virtual Uchitel Uchitel { get; set; }
    }
}
