//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urok
    {
        public int ID_Urok { get; set; }
        public string Weekday { get; set; }
        public int Nomer_uroka { get; set; }
        public int ID_Klass { get; set; }
        public int ID_Uchitel { get; set; }
        public int ID_K { get; set; }
        public int ID_Predmet { get; set; }
    
        public virtual Kabinet Kabinet { get; set; }
        public virtual Klass Klass { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual Uchitel Uchitel { get; set; }
    }
}
